= Update from 0.1.0 to 1.0.x

1.0.x requires Tailor https://github.com/opendevstack/tailor/releases/tag/v0.9.3[0.9.3].

== Update `xyz-cd` projects

There is a new webhook proxy now, which proxies webhooks sent from BitBucket to
Jenkins. As well as proxying, this service creates and deletes pipelines on the
fly, allowing to have one pipeline per branch. To update:

* Setup the image in the `cd` project by running `tailor update` in
`ods-core/jenkins/ocp-config`.
* Build the image.
* Setup the  webhook proxy next to each Jenkins instance. E.g., go to
`ods-project-quickstarters/ocp-templates/templates` and run
`oc process cd//cd-jenkins-webhook-proxy | oc create -f- -n xyz-cd`. Repeat for
each project.

== Update components (information for ODS users)

For each component, follow the following steps:

In `Jenkinsfile`:

. Set the shared library version to `1.0.x`.
. Replace `stageUpdateOpenshiftBuild` with `stageStartOpenshiftBuild`.
. Remove `stageCreateOpenshiftEnvironment` and `stageTriggerAllBuilds`.
. Adapt the build logic to match the latest state of the quickstarter
boilerplates.
. Remove `verbose: true` config (replace with `debug: true` if you want debug
output).
. Configure `branchToEnvironmentMapping`, see README.md. If you used
environment cloning, also apply the instructions for that.

In `docker/Dockerfile`:

* Adapt the content to match the latest state of the quickstarter boilerplates.
* No Nexus upload build artifact is required anymore, use a copy in Jenkins shell
command to docker folder (see in any boilerplate how it is done now).
* In BitBucket, remove the existing "Post Webhooks" and create a new "Webhook",
pointing to the new webhook proxy. The URL has to be of the form
`+https://webhook-proxy-$PROJECT_ID-cd.$DOMAIN?trigger_secret=$SECRET+`. As
events, select "Repository Push" and "Pull request Merged + Declined".

== Update provisioning app

If you want to build the provisioning app automatically when commits are pushed
to BitBucket, add a webhook as described in the previous section.

== Fix Jenkins master BUILD_URL

1.0.x makes use of the `BUILD_URL` env variable automatically set by Jenkins. This
env variable might be `null` in your Jenkins master. To fix this, copy
https://github.com/opendevstack/ods-core/blob/1.0.x/jenkins/master/configuration/init.groovy.d/url.groovy into each Jenins master to `/var/lib/jenkins/init.groovy.d/url.groovy`.

== Fix JSON patch replace error in Jenkins build

1.0.x sets image labels on the `BuildConfig` in Jenkins. It does this by issuing a JSON patch `replace` request to `/spec/output/imageLabels`. This path was not present in prior versions, which can lead to the following error: `Error from server: jsonpatch replace operation does not apply: doc is missing key: /spec/output/imageLabels`. For newly provisioned components, this has been fixed with https://github.com/opendevstack/ods-project-quickstarters/pull/188. For existing components, add the path to the `BuildConfig` manually by editing the YAML in OpenShift.
