= Update Guide for OpenDevStack administrators
:page-layout: documentation

Learn all about how to update your OpenDevStack repositories and the running
installation of it.

== How to update your OpenDevStack repositories

Updating repositories means that new refs from repositories under
`github.com/opendevstack` are pushed into the repositories in your BitBucket
instance. Note that only updates to the `production` branch in BitBucket will
have any effect on the OpenDevStack installation.

First, you need a clone of each repository in BitBucket which should be updated
on your local machine.

Once this has been done, you need to fetch new refs from
`github.com/opendevstack`. To do so, add a remote pointing to it like this:

[source,sh]
----
git remote add ods https://github.com/opendevstack/<REPO_NAME>.git
----

Now you are ready to update the refs. It is recommended to update both the
`master` branch and, unless you want to live off the bleeding edge, a release
branch such as `2.x`. Use the steps shown below:

[source,sh]
----
# Ensure you have the latest refs from ODS locally
git fetch ods
# Update master
git checkout master
git reset --hard ods/master
git push origin master
# Update 2.x
git checkout 2.x
git reset --hard ods/2.x
git push origin 2.x
----

If your OpenDevStack installation is based on the `production` branch, then you
need to create a pull request on BitBucket from `2.x` into `production` now.

Now that the repositories are updated, you also need to modify the images and the
running instances in OpenShift.

== How to update your OpenDevStack installation

Updating consists of two parts: following the general update procedure
(applicable to all version updates) and a version specific update procedure.

=== General update procedure

==== Backup

Before proceeding, it is advisable to make a backup of the existing OpenShift
configuration. This can be done easily with Tailor:

[source,sh]
----
# Backup CD project
tailor export -n cd > backup_CD.yml

# Backup provision app namespaces
tailor export -n prov-cd > backup_PROV_CD.yml
tailor export -n prov-dev > backup_PROV_DEV.yml
tailor export -n prov-test > backup_PROV_TEST.yml
----

Note that the executing user needs to have permissions to access all resources
in the `cd` namespaces for this to work properly.

==== Tailor

Next, update Tailor to the version corresponding to your new OpenDevStack
version, which is noted at the start of each version specific update procedure.

==== Configuration

Then, update/add/remove the configuration parameters (located in `ods-configuration`).
To do this, use the `./update` script located in `ods-core/configuration-sample`.

==== OCP resources

Next, run `tailor update` in `ods-core` and `ods-quickstarters` to bring all OCP resources (such as DC or BC) into sync. Review the diff produced by Tailor carefully, especially around changes to PVCs.

==== Images

After all OCP resources have been updated, you need to start a build for all build configs
in the `cd` namespace to create new images.

==== Provisioning App

Also, the provisioning app should be updated. To do that, run `tailor update`
in each `ocp-config` folder, and then trigger a build in Jenkins to redeploy the
service.


Now that the general procedure has been completed, you need to apply all the
update notes below which apply to your version change.
